### ISSUE TITLE
Command bar focus issue

### ISSUE THREAD

**Issue by tinywrkb** [dcchambers/vb4c#2]
vb4c still suffers from 1995eaton/chromium-vim#691. basyura/chromium-vim@7f3567946a03a0946d7971ff9c5ec6d7df95fb81 solves this.

**Comment by fow5040** [comment]
second this - while the 'F' functionality is certainly a more significant feature-breaking bug, this one is still a nuisance. Would greatly appreciate this being merged once you have the chance.

Still - very thankful you've taken the effort to create (and maintain) a fork of cVim - hoping to help out in the future!

**Comment by dcchambers** [comment]
Thanks for the heads up, @tinywrkb! I'll see if @basyura will open a PR against the vb4c fork.

**Comment by dcchambers** [comment]
Thanks for the heads up, @tinywrkb! I'l see if @basyura will open a PR against the vb4c fork. That commit is a bit old, if I can get a hold of them in the next day or two I'll let them submit a PR if they're able too, otherwise I'll go ahead and fix it myself.

**Comment by dcchambers** [comment]
Thanks for the heads up, @tinywrkb!

**Comment by dcchambers** [comment]
Merged the fix ~> #3
