### ISSUE TITLE
Can't find it in the Chrome store

### ISSUE THREAD

**Issue by elig0n** [dcchambers/vb4c#5]
https://chrome.google.com/webstore/search/vb4c?hl=en&_category=extensions

No results for "vb4c"
Make sure all words are spelled correctly, or try a different search.

**Comment by eastmancr** [comment]
I has not been approved by Google yet to appear on the Chrome Web Store. You must install it manually from `chrome://extensions`.
From the README:

> # Install
> - vb4c is a **Chrome Extension** and can be installed from the [Chrome Web Store.](https://chrome.google.com/webstore/search/vb4c?hl=en)
>   - This is a brand new release and it is currently pending review from Google. I will update the link here once it is available!
>   - In the mean time you can manually install the extension from the [releases](https://github.com/dcchambers/vb4c/releases) page on GitHub.
>     - Download the `.zip` file, extract it, and then manually load the
>       extension in chrome.
>       - Go to `chrome://extensions`
>       - Enable the developer mode toggle.
>       - Select 'Load Unpacked Extension'
>       - Navigate to the directory that you unzipped above.
>       - That's it!
