### ISSUE TITLE
Can't Search from Chrome Web Store

### ISSUE THREAD

**Issue by seonggukchoi** [dcchambers/vb4c#9]
https://chrome.google.com/webstore/search/vb4c?hl=en

**Comment by eastmancr** [comment]
Dup of issue #5 

I has not been approved by Google yet to appear on the Chrome Web Store. You must install it manually from `chrome://extensions`.
From the README:

> # Install
> - vb4c is a **Chrome Extension** and can be installed from the [Chrome Web Store.](https://chrome.google.com/webstore/search/vb4c?hl=en)
>   - This is a brand new release and it is currently pending review from Google. I will update the link here once it is available!
>   - In the mean time you can manually install the extension from the [releases](https://github.com/dcchambers/vb4c/releases) page on GitHub.
>     - Download the `.zip` file, extract it, and then manually load the
>       extension in chrome.
>       - Go to `chrome://extensions`
>       - Enable the developer mode toggle.
>       - Select 'Load Unpacked Extension'
>       - Navigate to the directory that you unzipped above.
>       - That's it!

**Comment by seonggukchoi** [comment]
@LemonJuiz
```This is a brand new release and it is currently pending review from Google.```
I didn't see this sentence. Thank you!
